import "@/public/global.css"
import Header from "@/components/Header"
import Footer from "@/components/Footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (<html lang="en" className="scroll-smooth">
    <body className="bg-gradient-to-br from-indigo-100 via-white to-cyan-100">
      <Header />
      {children}
      <Footer />
    </body>
  </html>)
}