import "@/public/global.css"

export const metadata = {
  title: 'Simeon Davenport\'s Portfolio',
  description: 'Generated by Next.js',
  name: "width=device-width, initial-scale=1.0"
}

export default function RootLayout({ children }) {
  return (<html lang="en" className="scroll-smooth">
    <head>
      <link rel="icon" href="favicon.ico" sizes="any" />
    </head>
    <body>{children}</body>
  </html>)
}